Controllers/CustomerController.cs
using CoraetionTask.Models;
using CoraetionTask.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Principal;

namespace CoraetionTask.Controllers
{
    
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IProductRepository _productRepository;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CustomerController(ICustomerRepository customerRepository, IProductRepository productRepository, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _productRepository = productRepository;
            _customerRepository = customerRepository;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            List<Customer> customersList = await _customerRepository.GetAllAsync();
            return View(customersList);
        }

        [Authorize(Roles ="Admin,User")]
        public async Task<IActionResult> Details(int id)
        {
            Customer customersDetails = await _customerRepository.GetByIdAsync(id,c=>c.Products);

            if (customersDetails == null) return View("NotFound");
            return View(customersDetails);
        }

        [HttpGet,Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            Customer customersDetails = await _customerRepository.GetByIDAsync(id);
            if (customersDetails == null) return View("NotFound");

            return View(customersDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Customer customer)
        {
            Customer customersDetails = await _customerRepository.GetByIDAsync(id);
            if (customersDetails == null) return View("NotFound");
            if (ModelState.IsValid)
            {
                await _customerRepository.UpdateAsync(id, customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        [HttpGet, Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            Customer customersDetails = await _customerRepository.GetByIDAsync(id);
            if (customersDetails == null) return View("NotFound");

            return View(customersDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            Customer customersDetails = await _customerRepository.GetByIDAsync(id);
            if (customersDetails == null) return View("NotFound");
            await _customerRepository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        
        [HttpGet, Authorize(Roles = "Admin")]
        public IActionResult Create(int id) => View();

        [HttpPost]
        public async Task<IActionResult> Create(int id, Customer customer)
        {

            if (ModelState.IsValid)
            {
                // check dublicated email
                Customer  existingEmail = await _customerRepository.GetCustomerByEmailAsync(customer.Email);

                if (existingEmail != null)
                {
                    ModelState.AddModelError("Email", "email is already taken");
                    return View(customer);
                }
                await _customerRepository.AddAsync(customer);

                // split full name spaces to make username
                string fullnameWithSpaces = customer.FullName;
                string[] nameParts = fullnameWithSpaces.Split(' ');

                string fullNameWithNoSpaces = string.Concat(nameParts);

                // add customer as user in the system
                IdentityUser newUser = new IdentityUser()
                {
                    UserName = fullNameWithNoSpaces,
                    Email = customer.Email,
                    PhoneNumber = customer.Mobile,
                };

                // save new user in database
                IdentityResult result = await _userManager.CreateAsync(newUser, customer.Password);

                if (result.Succeeded)
                {
                    if (await _roleManager.RoleExistsAsync("User"))
                    {
                        await _userManager.AddToRoleAsync(newUser, "User");
                    }
                    else
                    {
                        IdentityResult roleUser = await _roleManager.CreateAsync(new IdentityRole("User"));

                        await _userManager.AddToRoleAsync(newUser, "User");
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(customer);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Profile(int id)
        {
            Customer customersDetails = await _customerRepository.GetByIdAsync(id,c=>c.Products);
            //ViewBag.Products = await _productRepository.GetAllAsync();

            if (customersDetails == null) return View("NotFound");

            return View(customersDetails);
        }

        public async Task<IActionResult> BuyProduct() {
            ViewBag.Products = await _productRepository.GetAllAsync();
            return View(); 
        }

        [HttpPost,Authorize(Roles = "User")]
        public async Task<IActionResult> BuyProduct(int customerId, int[] productIds)
        {
            Customer customer = await _customerRepository.GetByIDAsync(customerId);

            if (customer == null)
            {
                return View("NotFound");
            }

            foreach (int productId in productIds)
            {
                Product product = await _productRepository.GetByIDAsync(productId);

                if (product != null)
                {
                    await _customerRepository.AddProductToCustomer(customerId, product);
                }
            }

            return RedirectToAction("Profile", new { id = customerId });
        }

    }
}

Controllers/ProductController.cs
using CoraetionTask.Models;
using CoraetionTask.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoraetionTask.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;

        private readonly ICustomerRepository _customerRepository;

        public ProductController(IProductRepository productRepository, ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index()
        {
            var productList = await _productRepository.GetAllAsync(u=>u.Customer);
            return View(productList);
        }

        public async Task<IActionResult> Details(int id)
        {
            Product productDetails = await _productRepository.GetByIDAsync(id);

            if (productDetails == null) return View("NotFound");
            return View(productDetails);
        }
        
        public async Task<IActionResult> Edit(int id)
        {
            Product productDetails = await _productRepository.GetByIDAsync(id);
            if (productDetails == null) return View("NotFound");

            return View(productDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            Product productDetails = await _productRepository.GetByIDAsync(id);
            if (productDetails == null) return View("NotFound");
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateAsync(id, product);
                return RedirectToAction("Index");
            }
            return View(product);
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            Product productDetails = await _productRepository.GetByIDAsync(id);

            if (productDetails == null) return View("NotFound");

            return View(productDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            Product productDetails = await _productRepository.GetByIDAsync(id);
            if (productDetails == null) return View("NotFound");
            await _productRepository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Create() =>  View();

        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {

            if (ModelState.IsValid)
            {
                await _productRepository.AddAsync(product);

                return RedirectToAction("Index");
            }
            return View(product);
        }
    }
}

Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor;
@{
    int? customerId = @Accessor.HttpContext.Session.GetInt32("customerId");
}

@if (!User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
    </li>
}
else if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
    </li>
    <li class="nav-item ms-auto">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Logout <strong>@User.Identity.Name</strong></a>
    </li>
}else{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-route-id="@customerId" asp-action="Profile">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="BuyProduct">BuyProduct</a>
    </li>
    <li class="nav-item ms-auto">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Logout <strong>@User.Identity.Name</strong></a>
    </li>
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Home" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoraetionTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #34495e;font-weight:bolder" asp-area="" asp-controller="Home" asp-action="Index">CoraetionTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container d-flex justify-content-center">
            &copy; 2023 - CoraetionTask - By Hazem Magdy - Made By <span style="color:red"> &hearts;&hearts;</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>